"""P2 core control plane

Revision ID: 2d80d962a004
Revises: 
Create Date: 2026-07-02 09:42:39.035818
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2d80d962a004'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=True),
    sa.Column('aggregate_id', sa.String(length=128), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dead_letter_commands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_message_id', sa.String(length=256), nullable=True),
    sa.Column('queue_name', sa.String(length=128), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=True),
    sa.Column('model_job_id', sa.String(length=128), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('command_schema_version', sa.String(length=64), nullable=True),
    sa.Column('delivery_attempt', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('detected_by', sa.String(length=128), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolution_status', sa.String(length=32), nullable=False),
    sa.Column('resolved_by', sa.String(length=128), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.CheckConstraint("resolution_status IN ('unresolved', 'acknowledged', 'replayed', 'discarded', 'resolved')", name='ck_dead_letter_resolution'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('request_kind', sa.String(length=64), nullable=False),
    sa.Column('result_ref', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_idempotency_key')
    )
    op.create_table('workspace_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('active_task_count', sa.Integer(), nullable=False),
    sa.Column('workspace_content_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('active', 'recovering', 'cleanup_pending', 'deleted', 'error')", name='ck_workspace_state'),
    sa.CheckConstraint('active_task_count >= 0', name='ck_workspace_task_count_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('created', 'queued', 'running', 'cancelling', 'completed', 'failed', 'cancelled', 'discarded')", name='ck_task_state'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_tasks_workspace_id'), 'application_tasks', ['workspace_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_sequence', sa.BigInteger(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'event_sequence', name='uq_event_workspace_sequence')
    )
    op.create_index(op.f('ix_outbox_events_workspace_id'), 'outbox_events', ['workspace_id'], unique=False)
    op.create_table('task_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('created', 'command_pending', 'dispatched', 'lease_acquired', 'running', 'committing', 'succeeded', 'failed_retryable', 'failed_final', 'cancelled')", name='ck_attempt_state'),
    sa.ForeignKeyConstraint(['task_id'], ['application_tasks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'attempt_number', name='uq_attempt_task_number')
    )
    op.create_index(op.f('ix_task_attempts_task_id'), 'task_attempts', ['task_id'], unique=False)
    op.create_table('model_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('current_command_generation', sa.Integer(), nullable=False),
    sa.Column('execution_lease_revision', sa.Integer(), nullable=False),
    sa.Column('worker_instance_id', sa.String(length=128), nullable=True),
    sa.Column('supervisor_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('queued', 'leased', 'loading_model', 'preprocessing', 'running', 'postprocessing', 'finalizing_artifacts', 'completed', 'lease_suspect', 'takeover_pending', 'recovery_required', 'cancelling', 'cancelled', 'cancelled_forced', 'discarded', 'failed')", name='ck_model_job_state'),
    sa.ForeignKeyConstraint(['attempt_id'], ['task_attempts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_jobs_attempt_id'), 'model_jobs', ['attempt_id'], unique=True)
    op.create_table('command_outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_job_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('command_generation', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('resolution_type', sa.String(length=32), nullable=True),
    sa.Column('acquired_lease_revision', sa.Integer(), nullable=True),
    sa.Column('lease_owner_instance_id', sa.String(length=128), nullable=True),
    sa.Column('dispatch_attempts', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("resolution_type IS NULL OR resolution_type IN ('succeeded', 'cancelled', 'discarded', 'failed')", name='ck_command_resolution_type'),
    sa.CheckConstraint("state IN ('pending', 'dispatching', 'dispatched', 'worker_received', 'lease_acquired', 'execution_started', 'resolved', 'failed_retryable', 'failed_final', 'cancelled', 'superseded')", name='ck_command_state'),
    sa.ForeignKeyConstraint(['attempt_id'], ['task_attempts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_job_id'], ['model_jobs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_outbox_attempt_id'), 'command_outbox', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_command_outbox_model_job_id'), 'command_outbox', ['model_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_command_outbox_model_job_id'), table_name='command_outbox')
    op.drop_index(op.f('ix_command_outbox_attempt_id'), table_name='command_outbox')
    op.drop_table('command_outbox')
    op.drop_index(op.f('ix_model_jobs_attempt_id'), table_name='model_jobs')
    op.drop_table('model_jobs')
    op.drop_index(op.f('ix_task_attempts_task_id'), table_name='task_attempts')
    op.drop_table('task_attempts')
    op.drop_index(op.f('ix_outbox_events_workspace_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_application_tasks_workspace_id'), table_name='application_tasks')
    op.drop_table('application_tasks')
    op.drop_table('workspace_sessions')
    op.drop_table('idempotency_records')
    op.drop_table('dead_letter_commands')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
