"""P8 ct_volumes and ct_annotations

Revision ID: 4702e77cf62c
Revises: 6bf5810a8f42
Create Date: 2026-07-11 20:57:22.846000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4702e77cf62c'
down_revision: Union[str, None] = '6bf5810a8f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ct_volumes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('shape', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spacing', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affine', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('orientation', sa.String(length=8), nullable=False),
    sa.Column('dtype', sa.String(length=32), nullable=False),
    sa.Column('scalar_min', sa.Float(), nullable=False),
    sa.Column('scalar_max', sa.Float(), nullable=False),
    sa.Column('window_center', sa.Float(), nullable=False),
    sa.Column('window_width', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ct_volumes_workspace_id'), 'ct_volumes', ['workspace_id'], unique=False)
    op.create_table('ct_annotations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ct_volume_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('plane', sa.String(length=16), nullable=False),
    sa.Column('slice_index', sa.Integer(), nullable=False),
    sa.Column('points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("plane IN ('axial', 'coronal', 'sagittal')", name='ck_annotation_plane'),
    sa.ForeignKeyConstraint(['ct_volume_id'], ['ct_volumes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ct_annotations_ct_volume_id'), 'ct_annotations', ['ct_volume_id'], unique=False)
    op.create_index(op.f('ix_ct_annotations_workspace_id'), 'ct_annotations', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ct_annotations_workspace_id'), table_name='ct_annotations')
    op.drop_index(op.f('ix_ct_annotations_ct_volume_id'), table_name='ct_annotations')
    op.drop_table('ct_annotations')
    op.drop_index(op.f('ix_ct_volumes_workspace_id'), table_name='ct_volumes')
    op.drop_table('ct_volumes')
    # ### end Alembic commands ###
