"""P5 history references reservations

Revision ID: 6bf5810a8f42
Revises: a690573bf986
Create Date: 2026-07-07 10:09:55.599840
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6bf5810a8f42'
down_revision: Union[str, None] = 'a690573bf986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_quotas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('storage_backend', sa.String(length=64), nullable=False),
    sa.Column('filesystem_identity', sa.String(length=256), nullable=False),
    sa.Column('quota_bytes', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_backend', 'filesystem_identity', name='uq_quota_backend_fs')
    )
    op.create_table('history_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('profile', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('preparing', 'snapshotting', 'writing_artifacts', 'verifying', 'ready', 'failed', 'cleanup_pending', 'deleting', 'deleted')", name='ck_history_state'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_records_workspace_id'), 'history_records', ['workspace_id'], unique=False)
    op.create_table('storage_reservations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reservation_type', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('operation_id', sa.String(length=128), nullable=True),
    sa.Column('storage_backend', sa.String(length=64), nullable=False),
    sa.Column('filesystem_identity', sa.String(length=256), nullable=False),
    sa.Column('reserved_bytes', sa.BigInteger(), nullable=False),
    sa.Column('consumed_bytes', sa.BigInteger(), nullable=False),
    sa.Column('reservation_status', sa.String(length=32), nullable=False),
    sa.Column('owner_instance_id', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("reservation_status IN ('active', 'released', 'expired')", name='ck_reservation_status'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('history_record_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('storage_status', sa.String(length=32), nullable=False),
    sa.Column('expected_chunk_count', sa.Integer(), nullable=True),
    sa.Column('expected_total_size', sa.BigInteger(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('verification_generation', sa.BigInteger(), nullable=False),
    sa.Column('verification_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("storage_status IN ('writing', 'verifying', 'verified', 'corrupted')", name='ck_history_artifact_status'),
    sa.ForeignKeyConstraint(['history_record_id'], ['history_records.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_artifacts_history_record_id'), 'history_artifacts', ['history_record_id'], unique=False)
    op.create_table('history_save_operations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('history_record_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_manifest_sha256', sa.String(length=64), nullable=True),
    sa.Column('snapshot_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['history_record_id'], ['history_records.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_save_operations_history_record_id'), 'history_save_operations', ['history_record_id'], unique=False)
    op.create_table('history_artifact_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['history_artifacts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'chunk_index', name='uq_chunk_artifact_index')
    )
    op.create_index(op.f('ix_history_artifact_chunks_artifact_id'), 'history_artifact_chunks', ['artifact_id'], unique=False)
    op.create_table('history_snapshot_references',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('save_operation_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('snapshot_path', sa.Text(), nullable=False),
    sa.Column('reference_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("reference_status IN ('active', 'released')", name='ck_snapshot_ref_status'),
    sa.ForeignKeyConstraint(['save_operation_id'], ['history_save_operations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_snapshot_references_save_operation_id'), 'history_snapshot_references', ['save_operation_id'], unique=False)
    op.create_table('workspace_source_references',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('save_operation_id', sa.Uuid(), nullable=False),
    sa.Column('reference_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("reference_status IN ('active', 'released')", name='ck_source_ref_status'),
    sa.ForeignKeyConstraint(['save_operation_id'], ['history_save_operations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_source_references_workspace_id'), 'workspace_source_references', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_source_references_workspace_id'), table_name='workspace_source_references')
    op.drop_table('workspace_source_references')
    op.drop_index(op.f('ix_history_snapshot_references_save_operation_id'), table_name='history_snapshot_references')
    op.drop_table('history_snapshot_references')
    op.drop_index(op.f('ix_history_artifact_chunks_artifact_id'), table_name='history_artifact_chunks')
    op.drop_table('history_artifact_chunks')
    op.drop_index(op.f('ix_history_save_operations_history_record_id'), table_name='history_save_operations')
    op.drop_table('history_save_operations')
    op.drop_index(op.f('ix_history_artifacts_history_record_id'), table_name='history_artifacts')
    op.drop_table('history_artifacts')
    op.drop_table('storage_reservations')
    op.drop_index(op.f('ix_history_records_workspace_id'), table_name='history_records')
    op.drop_table('history_records')
    op.drop_table('storage_quotas')
    # ### end Alembic commands ###
