"""P4 lease recovery budgets and worker binding

Revision ID: a690573bf986
Revises: 2d80d962a004
Create Date: 2026-07-07 09:47:20.202267
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a690573bf986'
down_revision: Union[str, None] = '2d80d962a004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command_outbox', sa.Column('delivery_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('command_outbox', sa.Column('lease_recovery_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('command_outbox', sa.Column('recovery_window_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('command_outbox', sa.Column('last_recovery_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('command_outbox', sa.Column('consecutive_recovery_failures', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('command_outbox', sa.Column('total_recovery_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('model_jobs', sa.Column('execution_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('model_jobs', sa.Column('worker_pid', sa.Integer(), nullable=True))
    op.add_column('model_jobs', sa.Column('child_process_uuid', sa.String(length=64), nullable=True))
    op.add_column('model_jobs', sa.Column('startup_nonce_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_jobs', 'startup_nonce_hash')
    op.drop_column('model_jobs', 'child_process_uuid')
    op.drop_column('model_jobs', 'worker_pid')
    op.drop_column('model_jobs', 'execution_attempts')
    op.drop_column('command_outbox', 'total_recovery_attempts')
    op.drop_column('command_outbox', 'consecutive_recovery_failures')
    op.drop_column('command_outbox', 'last_recovery_at')
    op.drop_column('command_outbox', 'recovery_window_started_at')
    op.drop_column('command_outbox', 'lease_recovery_attempts')
    op.drop_column('command_outbox', 'delivery_attempts')
    # ### end Alembic commands ###
